project:
  type: website
  output-dir: docs

website:
  title: "Data Projects — Acis18"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: projects/index.qmd
        text: Proyectos
    right:
      - icon: linkedin
        href: www.linkedin.com/in/angel-acis
        target: _blank
      - icon: github
        href: https://github.com/Acis18/data-projects
        target: _blank

format:
  html:
    theme: cyborg
    toc: true
    lang: es