project:
  type: website
  output-dir: docs

website:
  title: "Data Projects — Acis18"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/TUNOMBREDEUSUARIO
        target: _blank
      - icon: github
        href: https://github.com/Acis18/data-projects
        target: _blank
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Proyectos"

format:
  html:
    theme: cyborg
    toc: true
    lang: es